//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avales()
        {
            this.Avalan = new HashSet<Avalan>();
        }
    
        public int IdAval { get; set; }
        public string Nombre { get; set; }
        public string Domicilio { get; set; }
        public string Teléfono { get; set; }
        public string NoEscritura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avalan> Avalan { get; set; }
    }
}
